apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: souravsuman911/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/application.yml"
          volumeMounts:
            - name: api-gateway-config-volume
              mountPath: /config
      volumes:
        - name: api-gateway-config-volume
          configMap:
            name: api-gateway-config
